done
SofthouseVxo/tentamen2 pull request #11
Opened 2020-06-04 14:03 UTC by ahmedmsulub

2020-06-04 14:56 UTC, jonaseck2 requested changes

2020-06-04 14:56 UTC, jonaseck2 commented on index.js
> +listing = require("./routes/listing")
används inte va?

2020-06-04 14:56 UTC, jonaseck2 commented on index.js
> +app.use('/api/members', require('./routes/index'))
behövs inte, alla routes läggs till nere i:

```javascript
app.use('/', routes)
```

2020-06-04 14:56 UTC, jonaseck2 commented on routes/index.js
> +router.post("/", listing.post)
/ -> /listings

2020-06-04 14:56 UTC, jonaseck2 commented on routes/index.js
> +router.delete("/:id", listing.deleted)
/:id -> /listings/:id

2020-06-04 14:56 UTC, jonaseck2 commented on routes/listing.js
> +    Id: uuid.v4(),
Id lägger mongo till automagiskt, ta bort
kolla kodexemplena, har inte haft något sådant i dem...

2020-06-04 14:56 UTC, jonaseck2 commented on routes/listing.js
> +      Longitude: req.body.Longitude,
req.body.Longitude, -> req.body.Coordinate.Longitude,

Samma för latitude

2020-06-04 14:56 UTC, jonaseck2 commented on routes/listing.js
> +    .then(() => 'deleted');
Detta går ju inte att köra 'List deleted' är inte javaskript...

`res.json message({message})` kommer lägga message i ett tomt  objekt {}, varför inte `res.json message(message)`

Har blandat async await och promise här:

```javascript
Listing.findByIdAndRemove(req.params.id)
 .then((message) => res.json(message));
```

eller 

```javascript
  const message = await Listing.findByIdAndRemove(req.params.id);
    res.json(message))
```

funkar det ens om jag kör detta?

kolla kodexemplena om du är osäker

2020-06-04 14:56 UTC, jonaseck2 commented on routes/listing.js
> +    .then(() => 'List Found');
samma som ovan: antingen async await eller promise, inte båda

2020-06-04 14:56 UTC, jonaseck2 commented on routes/listing.js
> +      res.send(listing)
Här blir det ju rätt

2020-06-04 14:56 UTC, jonaseck2 commented on routes/listing.js
> +  res.json({ message });
svara 200 om tagits bort, annars 204

kolla kodexemplena

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +  /:
flytta till /listings

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +        '401':
Din app svarar aldrig 401, ta bort

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +  /:id:
ta bort

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +    delete:
flytta till /listings/:id

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +        '200':
saknar 204 med när inget togs bort

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +                $ref: "#/components/schemas/ResponseListings"
ResponseListings -> ResponseListing
är ett objekt du får tillbaka, inte en array

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +                $ref: "#/components/schemas/ResponseListings"
ResponseListings -> ResponseListing
är ett objekt du får tillbaka, inte en array

uppdatera beskrivningen med, det är itne en array of listings

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +                $ref: "#/components/schemas/ResponseListings"
ResponseListings -> ResponseListing
är ett objekt du får tillbaka, inte en array

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +                  $ref: "#/components/schemas/ResponseListings"
ResponseListings -> ResponseListing
är ett objekt du får tillbaka, inte en array

2020-06-04 14:56 UTC, jonaseck2 commented on swagger/swagger.yaml
> +          '200':
saknar 204 och 201

2020-06-05 06:42 UTC, jonaseck2 requested changes

2020-06-05 06:42 UTC, jonaseck2 commented on routes/listing.js
> +
var är din query pararamtere för type som du har dokumenterat i swagger?

2020-06-05 06:42 UTC, jonaseck2 commented on routes/listing.js
> +    res.status(400)
detta sätts efter att du skickat tillbaka din request så det borde krascha här, ta bort!

2020-06-05 06:42 UTC, jonaseck2 commented on swagger/swagger.yaml
> +        default:
du ska ha både responses default och responses 200, det var rätt i filen från början...

Du har ju gjort helt rätt längre ner så gör likadant här :)

2020-06-05 06:42 UTC, jonaseck2 commented on swagger/swagger.yaml
> +        - name: Type
snyggt och fint, bara implementera det i koden med :)

2020-06-05 06:42 UTC, jonaseck2 commented on swagger/swagger.yaml
> +      responses:
saknar response 201 som du har implementerat

2020-06-05 06:42 UTC, jonaseck2 commented on swagger/swagger.yaml
> +      responses:
default error har ju content precis som du har gjort för error ovanför

2020-06-06 12:02 UTC, jonaseck2 requested changes

2020-06-06 12:02 UTC, jonaseck2 commented on routes/listing.js
> +    res.sendStatus(400)
Den har jag kommenterat innan, varför är den kvar?

2020-06-06 12:02 UTC, jonaseck2 commented on routes/listing.js
> +    findType = { Type: req.query.Type }
Du använder ju inte findtype, se till att testa koden och inte bara skicka vad du tror jag vill ha...

2020-06-06 12:02 UTC, jonaseck2 commented on swagger/swagger.yaml
> +        default:
Denna kommentaren har du inte fixat. Gör det, annars får du inte godkänt

2020-06-06 12:02 UTC, jonaseck2 commented on swagger/swagger.yaml
> +          description: created api
Och så content

2020-06-06 16:16 UTC, ahmedmsulub commented on swagger/swagger.yaml
> +          description: created api
menar du att jag ska ta bort content, för när jag tar bort den så funkar inte swaggern

2020-06-08 12:46 UTC, jonaseck2 requested changes

2020-06-08 12:46 UTC, jonaseck2 commented on swagger/swagger.yaml
> +          description: created api
Bra att du frågar!

Ja, 201 ska ha content, du svara ju med en json som innehåller en listing:

```yaml
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Listing"
```

2020-06-08 12:46 UTC, jonaseck2 commented on swagger/swagger.yaml
> +          description: List have been found
content igen:

```yaml
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Listing"
```

2020-06-08 12:46 UTC, jonaseck2 commented on swagger/swagger.yaml
> +        default:
Du verkar ha missat vad responses i swagger beskriver:

du ska beskriva alla de svar som kan komma från din applikation för den pathen och metoden:

om din metod kan svara 200 och det du kan svara enligt ett dataschema beskrivet längst ner i filen:
Om något får fel kan du också svara ett felfall, default, som är alla andra fall än de du har beskrivit, default har också en content:

```yaml
      responses:
        "200":
          description: List listings
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseListings" (ResponseListing om det är ett objekt, ResponseListings om det är en array)
(om du har flera möjliga statuskoder i dina svar... beskriv alla status-koder du kan få, med content om det inte är en 204)
        default:
          description: unexpected error (inte list not found, då är det möjligen status 404, men bara om du har ett fall i koden där du kan svara 404 i just detta fallet, vilket du inte har)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
```

2020-06-08 12:46 UTC, jonaseck2 commented on swagger/swagger.yaml
> +          description: no user have been deleted
saknar default här:

```yaml
        default:
          description: list not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
```

2020-06-10 07:11 UTC, jonaseck2 commented
Godkänd

2020-06-10 07:11 UTC, closed without merging