first commit no swagger
SofthouseVxo/tentamen2 pull request #13
Opened 2020-06-04 17:13 UTC by oscar-thorin

2020-06-04 19:23 UTC, jonaseck2 requested changes

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +        console.log(err);
```javascript
listingRoutes.route("/").get(function (req, res, next) {
...
if(err) next(err)
//inte console.log(err) då hänger sig requesten ju, det var ju samma sist
```

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +      res.status(400).send(err);
```javascript
listingRoutes.route("/").post(function (req, res, next) {
...
if(err) next(err)
//bra att du svarar, men det är inte alltid 400, det finns andra fel som err kan vara
```

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +listingRoutes.route("/:id").delete((req, res) => {
```javascript
listingRoutes.route("/").delete(function (req, res, next) {
...
if(err) next(err)
//du svarar på olika sätt i get här och post ovanför vid fel
```

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +listingRoutes.route("/:id").put(function (req, res) {
Kolla kodexempel 11 put and patch för hur du gör en put:

finns inte objektet, ska objektet skapas och status ska vara 201 (created)
finns objektet ska det ersättas och status ska vara 200 (ok)
är objektet detsamma ska status vara 204 (no content)

kolla kodexemplena så är det enkelt att göra likadant

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +          next(err);
fuck yeah!

fast du glömde next i signaturen:
```javascript
listingRoutes.route("/:id"). findById(function (req, res, next) {
```

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +          next(err);
beautiful, brings a goddamn tear to my eye!

fast du glömde next i signaturen:
```javascript
listingRoutes.route("/:id").put(function (req, res, next) {
```

2020-06-04 19:23 UTC, jonaseck2 commented on index.js
> +app.use((err, req, res, next) => {
Den som fanns kollar om ett svar redan skickats eller inte, annars kraschar res.send:

```javascript
  if (res.headersSent) {	
    return next(err)	
  }
```

2020-06-05 04:06 UTC, oscar-thorin commented
Gjorde klart det sista nu med lite extra på delete och sen fixade Swagger.

2020-06-05 06:50 UTC, jonaseck2 requested changes

2020-06-05 06:50 UTC, jonaseck2 commented on swagger/swagger.yaml
> +  /listings/?name={location}:
detta är inte hur man gör queryparameterar

Du har ju implementerat queryparametern under routen get /listing, så den ska ligga där. 

Se https://swagger.io/docs/specification/describing-parameters/#query-parameters

2020-06-05 06:50 UTC, jonaseck2 commented on swagger/swagger.yaml
> +          in: path
`in: query` och `required: false` räcker bra för en queryparameter bara flytta den parametern till get /listing så är du klar

2020-06-06 01:25 UTC, oscar-thorin commented
Fixade query i Swagger nu, sorry att det tog tid. Sovit tills nu haha

2020-06-10 07:09 UTC, jonaseck2 commented
Godkänd

2020-06-10 07:09 UTC, closed without merging